/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicantProfile: typeof import('./src/components/ApplicantProfile.vue')['default']
    ApplicationForm: typeof import('./src/components/ApplicationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetPassword: typeof import('./src/components/SetPassword.vue')['default']
  }
}
